# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatCitybuf

class Boundaries(object):
    NONE = 0
    MultiPoint = 1
    MultiLineString = 2
    MultiSurface = 3
    CompositeSurface = 4
    Solid = 5
    MultiSolid = 6
    CompositeSolid = 7
