# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatCitybuf

class CityObjectType(object):
    Bridge = 0
    Building = 1
    BuildingPart = 2
    CityFurniture = 3
    CityObjectGroup = 4
    GenericCityObject = 5
    LandUse = 6
    OtherConstruction = 7
    PlantCover = 8
    SolitaryVegetationObject = 9
    TINRelief = 10
    Transportation = 11
    Tunnel = 12
    WaterBody = 13
