# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatCitybuf

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatCitybuf.LineString import LineString
from typing import Optional
np = import_numpy()

class MultiLineString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultiLineString()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMultiLineString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MultiLineString
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultiLineString
    def LineStrings(self, j: int) -> Optional[LineString]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = LineString()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MultiLineString
    def LineStringsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MultiLineString
    def LineStringsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def MultiLineStringStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    MultiLineStringStart(builder)

def MultiLineStringAddLineStrings(builder: flatbuffers.Builder, lineStrings: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(lineStrings), 0)

def AddLineStrings(builder: flatbuffers.Builder, lineStrings: int):
    MultiLineStringAddLineStrings(builder, lineStrings)

def MultiLineStringStartLineStringsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartLineStringsVector(builder, numElems: int) -> int:
    return MultiLineStringStartLineStringsVector(builder, numElems)

def MultiLineStringEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MultiLineStringEnd(builder)
