# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatCitybuf

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatCitybuf.Point import Point
from typing import Optional
np = import_numpy()

class MultiPoint(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultiPoint()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMultiPoint(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MultiPoint
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultiPoint
    def Points(self, j: int) -> Optional[Point]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MultiPoint
    def PointsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MultiPoint
    def PointsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def MultiPointStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    MultiPointStart(builder)

def MultiPointAddPoints(builder: flatbuffers.Builder, points: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(points), 0)

def AddPoints(builder: flatbuffers.Builder, points: int):
    MultiPointAddPoints(builder, points)

def MultiPointStartPointsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartPointsVector(builder, numElems: int) -> int:
    return MultiPointStartPointsVector(builder, numElems)

def MultiPointEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MultiPointEnd(builder)
