# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatCitybuf

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatCitybuf.Solid import Solid
from typing import Optional
np = import_numpy()

class MultiSolid(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MultiSolid()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMultiSolid(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MultiSolid
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MultiSolid
    def Shells(self, j: int) -> Optional[Solid]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Solid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # MultiSolid
    def ShellsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # MultiSolid
    def ShellsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def MultiSolidStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    MultiSolidStart(builder)

def MultiSolidAddShells(builder: flatbuffers.Builder, shells: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shells), 0)

def AddShells(builder: flatbuffers.Builder, shells: int):
    MultiSolidAddShells(builder, shells)

def MultiSolidStartShellsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartShellsVector(builder, numElems: int) -> int:
    return MultiSolidStartShellsVector(builder, numElems)

def MultiSolidEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return MultiSolidEnd(builder)
