# automatically generated by the FlatBuffers compiler, do not modify

# namespace: flatCitybuf

import flatbuffers
from flatbuffers.compat import import_numpy
from typing import Any
from flatCitybuf.Shell import Shell
from typing import Optional
np = import_numpy()

class Solid(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset: int = 0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Solid()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSolid(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Solid
    def Init(self, buf: bytes, pos: int):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Solid
    def Shells(self, j: int) -> Optional[Shell]:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = Shell()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Solid
    def ShellsLength(self) -> int:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Solid
    def ShellsIsNone(self) -> bool:
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def SolidStart(builder: flatbuffers.Builder):
    builder.StartObject(1)

def Start(builder: flatbuffers.Builder):
    SolidStart(builder)

def SolidAddShells(builder: flatbuffers.Builder, shells: int):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(shells), 0)

def AddShells(builder: flatbuffers.Builder, shells: int):
    SolidAddShells(builder, shells)

def SolidStartShellsVector(builder, numElems: int) -> int:
    return builder.StartVector(4, numElems, 4)

def StartShellsVector(builder, numElems: int) -> int:
    return SolidStartShellsVector(builder, numElems)

def SolidEnd(builder: flatbuffers.Builder) -> int:
    return builder.EndObject()

def End(builder: flatbuffers.Builder) -> int:
    return SolidEnd(builder)
